# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa

provider "kubernetes" {
  config_path = "/home/stollenaar/.kube/config"
}



provider "vault" {
  token   = data.aws_ssm_parameter.vault_root.value
  address = "https://vault.home.spicedelver.me"
}

